# Generated by Django 3.1.7 on 2021-04-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('product_name', models.CharField(max_length=30)),
                ('selling_price', models.IntegerField()),
                ('buying_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('stock_id', models.TextField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('stock_buying_price', models.IntegerField()),
                ('stock_selling_price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
