# Generated by Django 3.1.7 on 2021-05-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplier_product_id'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('delivary_address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=150)),
                ('delivery_within_what_time', models.CharField(max_length=150)),
                ('alternative_contact_name', models.CharField(max_length=150)),
                ('alternative_contact_number', models.CharField(max_length=150)),
                ('payment_method', models.CharField(max_length=150)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('quantity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
                ('delivery_charge', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('due', models.IntegerField()),
                ('payment_status', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.TextField()),
                ('user_id', models.TextField()),
                ('user_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(default='', max_length=30)),
                ('category_name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('buying_price', models.IntegerField(default=1)),
                ('selling_price', models.IntegerField(default=1)),
                ('purchase', models.IntegerField(default=1)),
                ('sale', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=1)),
                ('stock_buying_price', models.IntegerField(default=1)),
                ('stock_selling_price', models.IntegerField(default=1)),
                ('transaction_number', models.TextField(default=1)),
                ('tracking_number', models.TextField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pofit', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.customerinfo')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=10)),
                ('sup_name', models.CharField(max_length=50)),
                ('sup_email', models.CharField(max_length=50)),
                ('sup_contact', models.CharField(max_length=11)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products')),
            ],
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='storage',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.products'),
        ),
    ]
