# Generated by Django 3.1.7 on 2021-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210524_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='customer_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
