# Generated by Django 3.1.7 on 2021-05-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_user_details_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
    ]
