# Generated by Django 3.1.7 on 2021-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_invoice_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name_of_customer',
            field=models.CharField(default='', max_length=10),
        ),
    ]
