# Generated by Django 3.1.7 on 2021-05-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_invoice_name_of_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name_of_customer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
