# Generated by Django 3.1.7 on 2021-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210524_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name_of_product',
            field=models.CharField(default='', max_length=50),
        ),
    ]
