# Generated by Django 3.1.7 on 2021-05-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_invoice_name_of_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinfo',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='supplierinfo',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierinfo',
            name='sup_contact',
        ),
        migrations.RemoveField(
            model_name='supplierinfo',
            name='sup_email',
        ),
        migrations.RemoveField(
            model_name='supplierinfo',
            name='sup_name',
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='productId',
            field=models.CharField(default='', max_length=11),
        ),
    ]
