# Generated by Django 3.1.7 on 2021-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210524_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinfo',
            name='supplier_contact',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='supplier_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierinfo',
            name='supplier_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
