# Generated by Django 3.1.7 on 2021-05-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210524_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinfo',
            name='supplier_id',
        ),
    ]
