# Generated by Django 3.1.7 on 2021-05-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='product_id',
        ),
    ]
